"""JSON storage service for RV sessions"""

import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


class StorageService:
    """Service for storing and retrieving RV sessions"""

    def __init__(self, data_dir: str):
        self.data_dir = data_dir
        self.sessions_dir = os.path.join(data_dir, 'sessions')

    def _get_session_dir(self, session_id: str) -> str:
        """Get the directory path for a session"""
        return os.path.join(self.sessions_dir, session_id)

    def _get_session_path(self, session_id: str) -> str:
        """Get the JSON file path for a session"""
        return os.path.join(self._get_session_dir(session_id), 'session.json')

    def _get_session_markdown_path(self, session_id: str) -> str:
        """Get the markdown file path for a session"""
        return os.path.join(self._get_session_dir(session_id), 'session.md')

    def _generate_markdown(self, session: Dict) -> str:
        """Generate markdown summary for a session"""
        lines = []

        lines.append(f"# RV Session: {session.get('name', session['id'])}")
        lines.append('')
        lines.append(f"**Session ID:** {session['id']}")
        lines.append(f"**Created:** {session['createdAt']}")
        lines.append(f"**Reveal At:** {session['revealAt']}")
        lines.append(f"**Number of Targets:** {len(session['targets'])}")
        lines.append('')

        if session.get('notes'):
            lines.append('## Notes')
            lines.append('')
            lines.append(session['notes'])
            lines.append('')

        lines.append('## Targets')
        lines.append('')

        for i, target in enumerate(session['targets'], 1):
            lines.append(f"### Target {i}: {target['code']}")
            lines.append('')
            lines.append(f"**Code:** `{target['code']}`")
            status = 'Revealed' if target['revealed'] else 'Pending'
            lines.append(f"**Status:** {status}")
            lines.append(f"**Source:** {target['targetSource']}")

            if target['revealed']:
                lines.append('')
                lines.append('**Description:**')
                lines.append('')
                lines.append(target['targetDescription'])
                lines.append('')
                lines.append('**Image URL:**')
                lines.append('')
                lines.append(target['targetUrl'])
                lines.append('')
                if target.get('revealedAt'):
                    lines.append(f"**Revealed At:** {target['revealedAt']}")

            lines.append('')
            lines.append('---')
            lines.append('')

        lines.append('')
        lines.append('---')
        lines.append('')
        lines.append('*Generated by Glimpse RV Testing CLI*')

        return '\n'.join(lines)

    def ensure_data_directory(self):
        """Ensure the data directory exists"""
        Path(self.sessions_dir).mkdir(parents=True, exist_ok=True)

    def save_session(self, session: Dict):
        """Save a session to JSON and markdown files"""
        self.ensure_data_directory()

        session_dir = self._get_session_dir(session['id'])
        json_path = self._get_session_path(session['id'])
        md_path = self._get_session_markdown_path(session['id'])

        # Create session directory
        Path(session_dir).mkdir(parents=True, exist_ok=True)

        # Save JSON file
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(session, f, indent=2, ensure_ascii=False)

        # Save markdown file
        markdown = self._generate_markdown(session)
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(markdown)

    def get_session(self, session_id: str) -> Optional[Dict]:
        """Get a session by ID"""
        json_path = self._get_session_path(session_id)

        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except FileNotFoundError:
            return None

    def get_all_sessions(self) -> List[Dict]:
        """Get all sessions"""
        self.ensure_data_directory()

        sessions = []

        try:
            for entry in os.listdir(self.sessions_dir):
                entry_path = os.path.join(self.sessions_dir, entry)
                if os.path.isdir(entry_path):
                    session = self.get_session(entry)
                    if session:
                        sessions.append(session)
        except FileNotFoundError:
            return []

        # Sort by creation date (newest first)
        def get_datetime(session):
            try:
                dt = datetime.fromisoformat(session['createdAt'])
                # Make naive if it has timezone info
                if dt.tzinfo is not None:
                    dt = dt.replace(tzinfo=None)
                return dt
            except Exception:
                return datetime.min

        sessions.sort(key=get_datetime, reverse=True)

        return sessions

    def update_session(self, session_id: str, updates: Dict):
        """Update a session with partial data"""
        session = self.get_session(session_id)
        if not session:
            raise Exception(f'Session {session_id} not found')

        session.update(updates)
        self.save_session(session)

    def delete_session(self, session_id: str):
        """Delete a session"""
        session_dir = self._get_session_dir(session_id)

        try:
            shutil.rmtree(session_dir)
        except FileNotFoundError:
            raise Exception(f'Session {session_id} not found')
